default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lets_clean_up_development

test:
  <<: *default
  database: lets_clean_up_test

production:
  <<: *default
  database: lets_clean_up_production
  username: lets_clean_up
  password: <%= ENV['LETS_CLEAN_UP_DATABASE_PASSWORD'] %>
